{{- if .Values.benchmark.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.benchmark.serviceAccount.name }}
  labels:
    {{- include "benchmark-charts.labels" . | nindent 4 }}
  {{- with .Values.benchmark.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
