{{- if eq .Values.inference.framework "nim" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.inference.serviceName }}
  namespace: {{ .Values.inference.serviceNamespace }}
  labels:
    {{- include "inference-charts.labels" . | nindent 4 }}
    "app.kubernetes.io/component": "{{ .Values.inference.serviceName }}"
spec:
  replicas: {{ .Values.inference.modelServer.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "inference-charts.selectorLabels" . | nindent 6 }}
      "app.kubernetes.io/component": "{{ .Values.inference.serviceName }}"
  template:
    metadata:
      labels:
        {{- include "inference-charts.selectorLabels" . | nindent 8 }}
        "app.kubernetes.io/component": "{{ .Values.inference.serviceName }}"
      {{- with .Values.inference.modelServer.deployment.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- with .Values.inference.modelServer.deployment.nim.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: nim-server
        image: "{{ .Values.inference.modelServer.image.repository }}:{{ .Values.inference.modelServer.image.tag }}"
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        ports:
        - containerPort: 8000
          name: http
        env:
        {{- range $key, $value := .Values.inference.modelServer.deployment.nim.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        - name: NGC_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.inference.modelServer.deployment.nim.secrets.ngcApiKey.name }}
              key: {{ .Values.inference.modelServer.deployment.nim.secrets.ngcApiKey.key }}
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.inference.modelServer.deployment.nim.secrets.hfToken.name }}
              key: {{ .Values.inference.modelServer.deployment.nim.secrets.hfToken.key }}
        {{- with .Values.inference.modelServer.deployment.nim.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.inference.modelServer.deployment.resources.gpu | nindent 10 }}
        {{- if .Values.inference.modelServer.deployment.nim.shm.enabled }}
        volumeMounts:
        - name: dev-shm
          mountPath: /dev/shm
        {{- end }}
        {{- with .Values.inference.modelServer.deployment.nim.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.inference.modelServer.deployment.nim.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- if .Values.inference.modelServer.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.inference.modelServer.deployment.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.inference.modelServer.deployment.tolerations }}
      tolerations:
        {{- toYaml .Values.inference.modelServer.deployment.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.inference.modelServer.deployment.topologySpreadConstraints.enabled }}
      topologySpreadConstraints:
        {{- range .Values.inference.modelServer.deployment.topologySpreadConstraints.constraints }}
        - maxSkew: {{ .maxSkew }}
          topologyKey: {{ .topologyKey }}
          whenUnsatisfiable: {{ .whenUnsatisfiable }}
          labelSelector:
            matchLabels:
              "app.kubernetes.io/component": "{{$.Values.inference.serviceName}}"
        {{- end }}
      {{- end }}
      {{- if and .Values.inference.modelServer.deployment.podAffinity.enabled .Values.inference.modelServer.deployment.podAffinity.preferredDuringSchedulingIgnoredDuringExecution }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            {{- range .Values.inference.modelServer.deployment.podAffinity.preferredDuringSchedulingIgnoredDuringExecution }}
            - weight: {{ .weight }}
              podAffinityTerm:
                topologyKey: {{ .podAffinityTerm.topologyKey }}
                labelSelector:
                  matchLabels:
                    "app.kubernetes.io/component": "{{$.Values.inference.serviceName}}"
            {{- end }}
      {{- end }}
      {{- if .Values.inference.modelServer.deployment.nim.shm.enabled }}
      volumes:
      - name: dev-shm
        emptyDir:
          medium: {{ .Values.inference.modelServer.deployment.nim.shm.medium }}
          sizeLimit: {{ .Values.inference.modelServer.deployment.nim.shm.sizeLimit }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.inference.serviceName }}
  namespace: {{ .Values.inference.serviceNamespace }}
  labels:
    {{- include "inference-charts.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "inference-charts.selectorLabels" . | nindent 4 }}
    "app.kubernetes.io/component": "{{ .Values.inference.serviceName }}"
{{- end }}
